version: '3.9'
services:
  app:
    labels:
      # Включаем traefik для текущего сервиса
      - traefik.enable=true
      # Объявляем порт сервиса в докере для прослушки
      - traefik.http.services.app.loadbalancer.server.port=3000
      # Говорим трафику использовать этот хост в HTTP
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app.rule=Host(`brick-nn.sbs`)
      # Говорит traefik использовать объявленную публичную сеть
      - traefik.docker.network=traefik-public
      # Говорим traefik использовать этот хост в HTTPS
      - traefik.http.routers.app-https.entrypoints=https
      - traefik.http.routers.app-https.rule=Host(`brick-nn.sbs`)
      - traefik.http.routers.app-https.tls=true
      # Используем сервис `le` (Let's Encrypt) для получения сертификата
      - traefik.http.routers.app-https.tls.certresolver=le
      # Объявляем миддлвейр редиректа с HTTP на HTTPS
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      # Устанавливаем миддлвейр редиректа с HTTP на HTTPS
      - traefik.http.routers.app-http.middlewares=https-redirect
    networks:
      - traefik-public
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    env_file:
      - .env
#    volumes:
#     - /var/lib/docker/volumes/online-shop-front_data-certs/_data:/etc/nginx/ssl
    command: [ "npm", "run", "start" ]

  mongo:
    user: root
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    ports:
      - "27027:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    # сделать 'mkdir /home/mongodb_brick && touch /home/mongodb_brick/.dbshell && chown -R 999:999 /home/mongodb_brick'
    # нахуя? - не спрашивайте
    volumes: 
      - /home/mongodb_brick:/home/mongodb
      - /var/data/mongodb_brick:/data/db
    networks:
      - traefik-public

  mongo-express:
    user: root
    image: mongo-express
    restart: always
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_LOGIN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: ${MONGO_DSN}
    networks:
      - traefik-public



# Внешняя сеть для связи между контейнерами докера
networks:
  traefik-public:
    external: true
