version: '3.9'
services:
  app:
    labels:
      # Включаем traefik для текущего сервиса
      - traefik.enable=true
      # Объявляем порт сервиса в докере для прослушки
      - traefik.http.services.app.loadbalancer.server.port=8080
      # Настройка маршрута для API с префиксом /api
      - traefik.http.routers.app-api.rule=Host(`kzk.ooo`) && PathPrefix(`/api`)
      # Удаление префикса /api из пути
      - traefik.http.middlewares.strip-api.stripprefix.prefixes=/api
      # Применение миддлвейра для удаления префикса
      - traefik.http.routers.app-api.middlewares=strip-api
      # Настройка для HTTPS
      - traefik.http.routers.app-api.entrypoints=https
      - traefik.http.routers.app-api.tls=true
      - traefik.http.routers.app-api.tls.certresolver=le
      # Объявляем миддлвейр редиректа с HTTP на HTTPS
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      # Устанавливаем миддлвейр редиректа с HTTP на HTTPS
      - traefik.http.routers.app-api-http.middlewares=https-redirect
      - traefik.http.routers.app-api-http.rule=Host(`kzk.ooo`) && PathPrefix(`/api`)
      - traefik.http.routers.app-api-http.entrypoints=http
    networks:
      - traefik-public
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    expose:
      - "8080"
    env_file:
      - .env
#    volumes:
#     - /var/lib/docker/volumes/online-shop-front_data-certs/_data:/etc/nginx/ssl
    command: [ "npm", "run", "start" ]

  mongo:
    user: root
    image: mongo:latest
    restart: always
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    # сделать 'mkdir /home/mongodb_brick && touch /home/mongodb_brick/.dbshell && chown -R 999:999 /home/mongodb_brick'
    # нахуя? - не спрашивайте
    volumes: 
      - /home/mongodb_brick:/home/mongodb
      - /var/data/mongodb_brick:/data/db
    networks:
      - traefik-public

  mongo-express:
    user: root
    image: mongo-express
    restart: always
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_LOGIN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASS}
      ME_CONFIG_MONGODB_URL: ${MONGO_DSN}
    networks:
      - traefik-public



# Внешняя сеть для связи между контейнерами докера
networks:
  traefik-public:
    external: true
